"""
src/notifier/email_notifier.py
--------------------------------
Builds a styled HTML email digest and sends it via SMTP.
"""

import smtplib
import logging
import os
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)


class EmailNotifier:

    def __init__(self, email_config: dict):
        self.sender     = email_config["sender"]
        self.password   = email_config["password"]
        self.recipients = email_config["recipients"]
        self.smtp_host  = email_config.get("smtp_host", "smtp.gmail.com")
        self.smtp_port  = email_config.get("smtp_port", 587)

    # ─────────────── PUBLIC API ──────────────────────────

    def send_digest(self, articles: list[dict], dry_run: bool = False) -> bool:
        """
        Build and send the HTML digest email.
        If dry_run=True, saves HTML to file instead of sending.
        """
        if not articles:
            logger.warning("No articles to send in digest.")
            return False

        subject  = f"📰 NewsRadar Digest — {datetime.now().strftime('%B %d, %Y')}"
        html     = self._build_html(articles)

        if dry_run:
            path = self._save_html(html)
            print(f"  [Dry Run] Digest saved to: {path}")
            return True

        return self._send_email(subject, html)

    # ─────────────── HTML BUILDER ────────────────────────

    def _build_html(self, articles: list[dict]) -> str:
        """Generate a clean, styled HTML email."""
        article_cards = "\n".join(self._article_card(a) for a in articles)
        count  = len(articles)
        date   = datetime.now().strftime("%A, %B %d, %Y")
        sources = len({a["source"] for a in articles})

        return f"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  body       {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
                background: #f5f5f5; margin: 0; padding: 20px; color: #333; }}
  .container {{ max-width: 680px; margin: 0 auto; background: #fff;
                border-radius: 12px; overflow: hidden; box-shadow: 0 2px 12px rgba(0,0,0,.1); }}
  .header    {{ background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
                color: #fff; padding: 32px 28px; }}
  .header h1 {{ margin: 0 0 6px; font-size: 24px; letter-spacing: -0.5px; }}
  .header p  {{ margin: 0; opacity: .7; font-size: 14px; }}
  .stats     {{ display: flex; gap: 20px; margin-top: 16px; }}
  .stat      {{ background: rgba(255,255,255,.15); border-radius: 8px;
                padding: 8px 14px; font-size: 13px; }}
  .stat b    {{ display: block; font-size: 20px; }}
  .body      {{ padding: 24px 28px; }}
  .card      {{ border: 1px solid #eee; border-radius: 10px; padding: 18px;
                margin-bottom: 16px; transition: box-shadow .2s; }}
  .card:hover{{ box-shadow: 0 4px 16px rgba(0,0,0,.08); }}
  .card h3   {{ margin: 0 0 6px; font-size: 16px; line-height: 1.4; }}
  .card h3 a {{ color: #1a1a2e; text-decoration: none; }}
  .card h3 a:hover {{ color: #e94560; }}
  .meta      {{ font-size: 12px; color: #888; margin-bottom: 8px; }}
  .desc      {{ font-size: 14px; color: #555; line-height: 1.6; margin: 0; }}
  .tags      {{ margin-top: 10px; }}
  .tag       {{ display: inline-block; background: #f0f4ff; color: #3a57e8;
                border-radius: 4px; padding: 2px 8px; font-size: 11px;
                margin-right: 4px; font-weight: 600; }}
  .footer    {{ text-align: center; padding: 20px; font-size: 12px;
                color: #aaa; border-top: 1px solid #eee; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>📰 NewsRadar Digest</h1>
    <p>{date}</p>
    <div class="stats">
      <div class="stat"><b>{count}</b>articles</div>
      <div class="stat"><b>{sources}</b>sources</div>
    </div>
  </div>
  <div class="body">
    {article_cards}
  </div>
  <div class="footer">
    Generated by <strong>NewsRadar</strong> · Automated News Digest Bot
  </div>
</div>
</body>
</html>
"""

    @staticmethod
    def _article_card(article: dict) -> str:
        keywords = article.get("matched_keywords", "")
        tags = "".join(
            f'<span class="tag">#{kw.strip()}</span>'
            for kw in keywords.split(",") if kw.strip()
        )
        desc = article.get("description", "")[:200] + ("..." if len(article.get("description", "")) > 200 else "")
        source = article.get("source", "Unknown")
        published = article.get("published_at", "")[:16]

        return f"""
<div class="card">
  <h3><a href="{article['url']}" target="_blank">{article['title']}</a></h3>
  <div class="meta">🗞 {source} &nbsp;·&nbsp; 🕐 {published}</div>
  <p class="desc">{desc}</p>
  <div class="tags">{tags}</div>
</div>"""

    # ─────────────── SMTP SEND ───────────────────────────

    def _send_email(self, subject: str, html: str) -> bool:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"]    = self.sender
        msg["To"]      = ", ".join(self.recipients)
        msg.attach(MIMEText(html, "html"))

        try:
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                server.ehlo()
                server.starttls()
                server.login(self.sender, self.password)
                server.sendmail(self.sender, self.recipients, msg.as_string())
            logger.info(f"Digest sent to {self.recipients}")
            return True
        except Exception as e:
            logger.error(f"Failed to send email: {e}")
            return False

    @staticmethod
    def _save_html(html: str) -> str:
        os.makedirs("outputs", exist_ok=True)
        path = f"outputs/digest_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)
        return path
